apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: sno-du-okd-v4-19
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJmYWtlIjogewogICAgICAiYXV0aCI6ICJhV1E2Y0dGemN3bz0iCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
