---
- set_fact:
    ocloud_workloads_list: "{{ ocloud_workloads | split(',') }}"

- name: Deploy workload - OAI CU-CP
  ansible.builtin.import_role:
    name: "ocloud_workload_oaicucp"
  when: '"oaicucp" in ocloud_workloads_list'
