---
- name: Include platform role - {{ ocloud_platform }}
  ansible.builtin.import_role:
    name: "ocloud_platform_okd"
  delegate_to: "{{ groups['deployer'][0] }}"
  run_once: true
  when: ocloud_platform == "okd"

- name: Include infra role - {{ ocloud_infra }}
  ansible.builtin.import_role:
    name: "ocloud_infra_vm"
  delegate_to: "{{ groups['kvm'][0] }}"
  when: ocloud_infra == "vm" and ocloud_platform_image is defined

- name: Include infra role - {{ ocloud_infra }}
  ansible.builtin.import_role:
    name: "ocloud_infra_baremetal"
  delegate_to: "{{ groups['deployer'][0] }}"
  when: ocloud_infra == "baremetal" and ocloud_platform_image is defined

- meta: flush_handlers

- name: Include platform role - Stolostron
  ansible.builtin.import_role:
    name: "ocloud_platform_stolostron"
  delegate_to: "{{ groups['deployer'][0] }}"
  run_once: true
  when: ocloud_platform == "okd"

- name: Include platform role - SiteConfig
  ansible.builtin.import_role:
    name: "ocloud_platform_siteconfig"
  delegate_to: "{{ groups['deployer'][0] }}"
  run_once: true
  when: ocloud_platform == "okd"

- name: Include platform role - ClusterGroupUpgrades
  ansible.builtin.import_role:
    name: "ocloud_platform_cgu"
  delegate_to: "{{ groups['deployer'][0] }}"
  run_once: true
  when: ocloud_platform == "okd"

- name: Include platform role - MultiClusterObservability
  ansible.builtin.import_role:
    name: "ocloud_platform_mco"
  delegate_to: "{{ groups['deployer'][0] }}"
  run_once: true
  when: ocloud_platform == "okd"

- name: Include platform role - oran-o2ims
  ansible.builtin.import_role:
    name: "ocloud_platform_o2ims"
  delegate_to: "{{ groups['deployer'][0] }}"
  run_once: true
  when: ocloud_platform == "okd"

- name: Include platform role - oran-hwmgr-plugin
  ansible.builtin.import_role:
    name: "ocloud_platform_hwmgr"
  delegate_to: "{{ groups['deployer'][0] }}"
  when: ocloud_platform == "okd"
