---
- name: Open port in firewall for DNS
  ansible.posix.firewalld:
    port: "53/udp"
    permanent: true
    immediate: true
    state: enabled
    zone: "{{ item }}"
  loop:
    - internal
    - public

- name: Open port in firewall for DHCP
  ansible.posix.firewalld:
    port: "67/udp"
    permanent: true
    immediate: true
    state: enabled
    zone: "{{ item }}"
  loop:
    - internal
    - public
  when: use_dhcp | bool
