http_store_container_name: http_store
http_store_pod_name: http_store_pod
http_dir: /opt/http_store
http_data_dir: "{{ http_dir }}/data"
http_port: 80
# Note if you change this you might have to change the env vars and volumes for podman task
container_image: quay.io/fedora/httpd-24:latest
file_owner: "{{ ansible_env.USER }}"
file_group: "{{ file_owner }}"

http_store_dir : "{{ iso_download_dest_path | default('/opt/http_store/data') }}"
http_port: 80
http_host: "{{ discovery_iso_server | default('http://' + hostvars['http_store']['ansible_host']) }}:{{ http_port }}"
test_file_name: http_test
