working_dir: "{{ ocloud_platform_okd_staging_dir }}"
generated_dir: "{{ working_dir['path'] }}/generated"

sshkeys_dir: "{{ working_dir['path'] }}/sshkeys"
sshkeys_public: "{{ cluster_name }}.pub"
sshkeys_private: "{{ cluster_name }}"

manifests_dir: "{{ generated_dir }}/{{ cluster_name }}"
cluster_manifest_dir: "{{ manifests_dir }}/cluster-manifests"
extra_manifest_dir: "{{ manifests_dir }}/openshift"
mac_interface_default_mapping: "interfaces[?(name != null && mac != null)].{logical_nic_name: name, mac_address: mac}"
static_network_config: {}
arch: x86_64
version_filter: "[?(openshift_version == '{{ openshift_version }}') && (cpu_architecture == '{{ arch }}')]"
release_image: "{{ (assisted_installer_release_images | json_query(version_filter))[0].url }}"

mirror_registry_fqdn: "{{ hostvars['registry_host']['registry_fqdn'] | default(hostvars['registry_host']['ansible_fqdn']) }}"
mirror_registry_port: "{{ hostvars['registry_host']['registry_port'] | default(5000) }}"
mirror_registry: "{{ mirror_registry_fqdn }}:{{ mirror_registry_port }}"

ocp_registry_namespace: "{{ hostvars['registry_host']['registry_namespace'] | default('ocp4') }}"
ocp_registry_image: "{{ hostvars['registry_host']['registry_image'] | default('openshift4') }}"
registry_repository: "{{ ocp_registry_namespace }}/{{ ocp_registry_image }}"
agent_based_installer_bootstrap_node: "{{ groups['masters'][0] }}"
host_ip_keyword: ansible_host
use_local_mirror_registry: "{{ setup_registry_service | default(true) }}"
single_node_openshift_enabled: "{{ is_valid_single_node_openshift_config | default(false) }}"

manifests: true
extra_manifests: []
manifest_templates: "{{ extra_manifests }}"

fetched_dest: "{{ repo_root_path }}/fetched"

api_vips: "{% if extra_api_vip is defined %}{{ [api_vip] + [extra_api_vip] }}{% else %}{{ [api_vip] }}{% endif %}"
ingress_vips: "{% if extra_ingress_vip is defined %}{{ [ingress_vip] + [extra_ingress_vip] }}{% else %}{{ [ingress_vip] }}{% endif %}"

ocp_version_major: "{{ openshift_version }}"


pull_secret: "{{ ocloud_platform_okd_pull_secret }}"

# target_name is the hostname for which the template will be rendered. The reason for this variable is
# becuase this role is used in two roles (setup_vm_host_network & generate_discovery_iso).
# This default will be used in setup_vm_host_network, while generate_discovery_iso will set target_name
# with the host which the nmstate is being rendered for.
target_name: "{{ inventory_hostname }}"

# The subnet on which all nodes are (or will be) accessible.¬
machine_network_cidr: 10.60.0.0/24¬

# The IP address pool to use for service IP addresses¬
service_network_cidr: 172.30.0.0/16¬

# Cluster network settings. You are unlikely to need to change these¬
cluster_network_cidr: 10.128.0.0/14 # The subnet, internal to the cluster, on which pods will be assigned IPs¬
cluster_network_host_prefix: 23 # The subnet prefix length to assign to each individual node.¬
