---
- name: Clone cluster-group-upgrades repo
  ansible.builtin.git:
    repo: "{{ ocloud_platform_cgu_repo_url }}"
    dest: "{{ ocloud_staging_dir['path'] }}/git/cluster-group-upgrades"

- name: Install cluster-group-upgrades
  ansible.builtin.shell:
    chdir: "{{ ocloud_staging_dir['path'] }}/git/cluster-group-upgrades"
    cmd: "make install deploy VERSION={{ ocloud_platform_cgu_version }}"
  environment:
    PATH: "{{ ocloud_staging_dir['path'] }}/go/bin:{{ ansible_env.PATH }}"
    KUBECONFIG: "{{ ocloud_kubeconfig }}"
