ai_version: v2.26.0
controller_tag: "{{ ai_version }}"
installer_agent_tag: "{{ ai_version }}"
installer_tag: "{{ ai_version }}"
assisted_service_tag: "{{ ai_version }}"
assisted_service_gui_tag: "{{ ai_version }}"
assisted_service_image_service_tag: "{{ ai_version }}"

get_release_images: true
get_all_release_versions: false

images_to_get_hash_for: "{{ assisted_installer_images | combine(processed_release_images | default({})) }}"

destination_hosts:
  - bastion
  - localhost
  - registry_host
  - assisted_installer

image_hashes_path: "{{ repo_root_path }}/image_hashes.yml"
ignore_cached_image_hashes: false
image_hashes: {}

assisted_service_image_repo_url: quay.io/edge-infrastructure

assisted_installer_images:
  controller:
    url: "{{ assisted_service_image_repo_url }}/assisted-installer-controller:{{ controller_tag }}"
  installer_agent:
    url: "{{ assisted_service_image_repo_url }}/assisted-installer-agent:{{ installer_agent_tag }}"
  installer:
    url: "{{ assisted_service_image_repo_url }}/assisted-installer:{{ installer_tag }}"
  service:
    url: "{{ assisted_service_image_repo_url }}/assisted-service:{{ assisted_service_tag }}"
  gui:
    url: "{{ assisted_service_image_repo_url }}/assisted-installer-ui:{{ assisted_service_gui_tag }}"
  image_service:
    url: "{{ assisted_service_image_repo_url }}/assisted-image-service:{{ assisted_service_image_service_tag }}"
