---
- name: Deploy OKD Cluster
  hosts: bastion
  vars:
    extract_installer: false
    generate_ssh_key_pair: true
  tasks:
    - name: Create staging dir for OKD installation
      ansible.builtin.tempfile:
        state: directory
      register: ocloud_platform_okd_staging_dir

- name: Extract Agent based installer
  ansible.builtin.import_playbook: extract_installer.yml
  when: (extract_installer | default(true)) | bool

- name: Generate SSH Key for node access
  ansible.builtin.import_playbook: generate_ssh_key_pair.yml
  when: (generate_ssh_keys | default(true)) | bool

- name: Generate ABI input manfiests
  ansible.builtin.import_playbook: generate_manifests.yml

# - name: Generate boot iso using ABI
#   ansible.builtin.import_playbook: generate_agent_iso.yml

# - name: Boot ISO
#   ansible.builtin.import_playbook: boot_iso.yml
#   vars:
#     boot_iso_hosts: masters,workers

# - name: Monitior installation
#   ansible.builtin.import_playbook: monitor_agent_based_installer.yml
