---
# - name: Validate Inventory
#   ansible.builtin.import_playbook: validate_inventory.yml

- name: Play to populate image_hashes for relevant images
  hosts: localhost
  gather_facts: false
  vars:
    SETUP_REGISTRY_SERVICE: "{{ (setup_registry_service | default(true)) | bool }}"
    destination_hosts:
      - registry_host
  pre_tasks:
    - name: Setup facts
      ansible.builtin.setup:
      when: SETUP_REGISTRY_SERVICE | bool
    - name: Pre-compute need to get hashes
      ansible.builtin.set_fact:
        run_get_hash: "{{ image_hashes | default({}) | length == 0 }}"
  roles:
    - role: redhatci.ocp.get_image_hash
      when: run_get_hash

- name: Play to install and setup mirror registry
  hosts: registry_host
  gather_facts: false
  vars:
    downloads_path: /tmp/wip
    config_file_path: /tmp/wip/config
    SETUP_REGISTRY_SERVICE: "{{ (setup_registry_service | default(true)) | bool }}"
  pre_tasks:
    - name: Setup facts
      ansible.builtin.setup:
      when: SETUP_REGISTRY_SERVICE | bool
  roles:
    - role: redhatci.ocp.setup_selfsigned_cert
      when: SETUP_REGISTRY_SERVICE | bool
    - role: redhatci.ocp.setup_mirror_registry
      when: SETUP_REGISTRY_SERVICE | bool

- name: Populate Registry
  ansible.builtin.import_playbook: populate_registry.yml
