---
- name: Validate Inventory
  ansible.builtin.import_playbook: playbooks/validate_inventory.yml

- name: Display deployment plan
  ansible.builtin.import_playbook: playbooks/display_deployment_plan.yml

- name: Deploy prerequisites
  ansible.builtin.import_playbook: deploy_prerequisites.yml

- name: Deploy cluster
  ansible.builtin.import_playbook: deploy_cluster.yml

- name: Post install
  ansible.builtin.import_playbook: post_install.yml

- name: Deploy day2 workers
  ansible.builtin.import_playbook: deploy_day2_workers.yml
  when: not ((use_agent_based_installer | default(true)) | bool)
