---
ocloud_workload_oaicucp_repo_url: "https://gitlab.eurecom.fr/oai/orchestration/charts.git"
ocloud_workload_oaicucp_repo_version: "main"
ocloud_workload_oaicucp_namespace: "oai-cu-cp"
ocloud_workload_oaicucp_helm_url: "https://get.helm.sh/helm-v3.18.2-linux-amd64.tar.gz"
ocloud_workload_oaicucp_amf_host: "oai-amf.oai-5g.svc"
ocloud_workload_oaicucp_image_url: "docker.io/oaisoftwarealliance/oai-gnb"
ocloud_workload_oaicucp_image_tag: "develop"
