---
- name: Extract OKD installer
  ansible.builtin.shell:
    cmd: "oc adm release extract --command=openshift-install {{ ocloud_platform_okd_base_url }}:{{ ocloud_platform_okd_release }} --to {{ ocloud_staging_dir['path'] }}/bin"
  environment:
    PATH: "{{ ocloud_staging_dir['path'] }}/bin:{{ ansible_env.PATH }}"

- name: Template OKD configs
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ocloud_staging_dir['path'] }}/cfg/{{ item }}"
  loop:
    - agent-config.yaml
    - install-config.yaml

- name: Copy MachineConfig manifests
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ocloud_staging_dir['path'] }}/cfg/openshift/{{ item }}"
  loop:
    - 99-master-pvs.yaml

- ansible.builtin.debug:
    verbosity: 2
    msg: "{{ lookup('file', [ocloud_staging_dir['path'], 'cfg', item] | path_join) }}"
  loop:
    - agent-config.yaml
    - install-config.yaml

- name: Generate OKD agent-based installer image
  ansible.builtin.shell:
    cmd: "openshift-install agent create image --dir {{ ocloud_staging_dir['path'] }}/cfg"
  environment:
    PATH: "{{ ocloud_staging_dir['path'] }}/bin:{{ ansible_env.PATH }}"

- debug:
    msg: |
       OKD agent-based installer image has been created as {{ ocloud_staging_dir['path'] }}/cfg/agent.x86_64.iso
       kubeconfig and kubeadmin-password can be found under {{ ocloud_staging_dir['path'] }}/cfg/auth/

- ansible.builtin.set_fact:
    ocloud_kubeconfig: "{{ ocloud_staging_dir['path'] }}/cfg/auth/kubeconfig"

- ansible.builtin.set_fact:
    ocloud_platform_image: "{{ ocloud_staging_dir['path'] }}/cfg/agent.x86_64.iso"
