---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset: all

- include_tasks: version.yml
  when: ocloud_platform_okd_kubeconfig

- include_tasks: install.yml
  when: ocloud_platform_okd_installed_release != ocloud_platform_okd_release
